In [1]:
#1.Write a program to generate two arrays of 5 random integers between 1 and 120 (mean square error). 
import numpy as np
def mse(a,p):
    return np.mean((a-p)**2)
actual=np.random.randint(1,20,5)
predicted=np.random.randint(1,120,5)
print(actual)
print(predicted)
print(mse(actual,predicted))

[ 3 15  1 15 18]
[55 53 53 40 72]
2078.6


In [2]:
#2.Write a program to implement sigmoid function in numpy. 
import numpy as np
def sigmoid(x):
    return 1/(1+np.exp(-x))
x=np.arange(1,11)
print(sigmoid(x))

[0.73105858 0.88079708 0.95257413 0.98201379 0.99330715 0.99752738
 0.99908895 0.99966465 0.99987661 0.9999546 ]


In [2]:
#3.  Write a program to implement softmax function using numpy*
import numpy as np
def softmax(arr):
    exp_values=np.exp(arr-np.max(arr))
    probabilities=exp_values/np.sum(exp_values)
    return probabilities
arr=[2.0,1.0,0.1]
print(softmax(arr))

[0.65900114 0.24243297 0.09856589]
